JJ_c_contact_l:
- 40um
- 40um
- 40um
JJ_c_contact_r:
- 2.5um
- 2.5um
- 2.5um
JJ_c_contact_shortl:
- 10um
- 10um
- 10um
JJ_c_contact_w:
- 10um
- 10um
- 10um
JJ_cutout_h:
- 70um
- 70um
- 70um
JJ_cutout_r:
- 150um
- 150um
- 150um
JJ_cutout_w:
- 70um
- 70um
- 70um
chip:
- main
- main
- main
coupling_d:
- 80um
- 70um
- 70um
coupling_gap:
- 30um
- 30um
- 20um
coupling_pad_w:
- 100um
- 200um
- 100um
coupling_r:
- 40um
- 40um
- 40um
coupling_stub_w:
- 90um
- 70um
- 90um
cpw_l:
- 100um
- 150um
- 100um
cpw_pin:
- 15 um
- 15 um
- 15 um
cut_h:
- 1000um
- 1100um
- 650um
cut_l:
- 600um+400um+400um
- 600um+400um+400um
- 450um+250um+250um
gap:
- 70um
- 70um
- 70um
istunnel:
- 'False'
- 'False'
- 'False'
jj_contact_size:
- 3um
- 3um
- 3um
jj_gap:
- 3um
- 3um
- 3um
junction:
- 'False'
- 'False'
- 'False'
junction_taper_r:
- 10um
- 10um
- 10um
l:
- 550um
- 880um
- 510um
orientation:
- '0'
- '0'
- '0'
r:
- 400um/2
- 400um/2
- 250um/2
resolution:
- '10'
- '10'
- '10'
w:
- 400um
- 400um
- 250um
